# Generated by Django 4.1.7 on 2023-03-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='following',
            new_name='follows',
        ),
    ]
