# Generated by Django 4.1.7 on 2023-03-27 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_following_customuser_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
