# Generated by Django 4.1.7 on 2023-03-27 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_customuser_follows_userfollows'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follow',
            field=models.ManyToManyField(related_name='follows', through='authentication.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
    ]
