# Generated by Django 4.1.7 on 2023-03-27 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_customuser_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
